### ISSUE TITLE
duplicate content type handler for text/x-vcard

### ISSUE THREAD

**Issue by phluid61** [troelskn/konstrukt#20]
In `lib/konstrukt/response.inc.php` the array `$GLOBALS['konstrukt_content_types']` has duplicate entries for key `'text/x-vcard'`:

```php
#line 17
  'text/x-vcard'  => 'vcard',
#...
#line 29
  'text/x-vcard' => 'vcf'
```

Pulled 2012-08-08.

**Comment by lsolesen** [comment]
@phluid61 Do you know which one is correct?

**Comment by troelskn** [comment]
Looks like it should be the latter, since there is a `k_VcfResponse` and no `k_VcardResponse`. That would also preserve current behaviour, as last key will override the prior.

**Comment by phluid61** [comment]
Yeah, I'm about 4 years out of touch, but I'd go with @troelskn's suggestion.
